# Site settings
title: ROCITY
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rocity.pw" # the base hostname & protocol for your site
twitter_username: iamkvnpl
github_username: rocity

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]